Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: weaviate
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: weaviate deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: weaviate
    Description: weaviate
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: centos_7_9_x64_20G_alibase_20240403.vhd
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 5
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
        #!/bin/bash
        yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum makecache
        yum install -y curl git docker-ce
        mkdir -p /etc/docker/
        echo '{
            "default-address-pools": [
                {
                    "base": "10.255.0.0/16",
                    "size": 24
                }
            ]
        }' > /etc/docker/daemon.json

        prefixChinaRegion="cn-"
        region=$(curl -s http://100.100.100.200/latest/meta-data/region-id)

        if [[ ${region} == ${prefixChinaRegion}* && ${region} != "cn-hongkong" ]]; then
          echo '{
              "default-address-pools": [
                  {
                      "base": "10.255.0.0/16",
                      "size": 24
                  }
              ],
              "registry-mirrors": [
                  "https://mirrors-ssl.aliyuncs.com/"
              ]
          }' > /etc/docker/daemon.json
        fi

        sudo systemctl enable --now docker.socket
        sudo systemctl enable --now docker.service

        mkdir -p /root/weaviate
        cat << EOF > /root/weaviate/docker-compose.yml
        name: weaviate
        services:
          weaviate:
            command:
              - --host
              - 0.0.0.0
              - --port
              - "8080"
              - --scheme
              - http
            environment:
              AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
              AUTHENTICATION_APIKEY_ALLOWED_KEYS: user-a-key,user-b-key
              AUTHENTICATION_APIKEY_ENABLED: "false"
              AUTHENTICATION_APIKEY_USERS: user-a,user-b
              AUTHORIZATION_ENABLE_RBAC: "true"
              ENABLE_API_BASED_MODULES: "true"
              PERSISTENCE_DATA_PATH: /var/lib/weaviate
              QUERY_DEFAULTS_LIMIT: "25"
            image: cr.weaviate.io/semitechnologies/weaviate:1.29.1
            networks:
              default: null
            ports:
              - mode: ingress
                target: 8080
                published: "8080"
                protocol: tcp
              - mode: ingress
                target: 50051
                published: "50051"
                protocol: tcp
            restart: on-failure:0
            volumes:
              - type: volume
                source: weaviate_data
                target: /var/lib/weaviate
                volume: {}
        networks:
          default:
            name: app_default
        volumes:
          weaviate_data:
            name: app_weaviate_data
        EOF
        cd /root/weaviate
        docker compose up -d